[package]
name = "poe-ladder"
version = "0.1.0"
authors = ["David Herberth <github@dav1d.de>"]
edition = "2018"


[dependencies]
poe-api = { path = "../poe-api" }
tokio = { version = "0.2", features = ["full"] }
futures = "0.3"
clap = "2"
human_format = "1.0"

